-- Seed 100 example plates into the plates table
-- Run this in Supabase SQL Editor after running schema.sql

INSERT INTO public.plates (text, state, rarity, category, ai_primary, difficulty, validated) VALUES
('GR8FUL',   'CA', 'common',    'phonetic',           'Grateful',                                            1, true),
('LV2RUN',   'OR', 'common',    'phonetic',           'Love to run',                                         1, true),
('H8MNDY',   'TX', 'common',    'phonetic',           'Hate Monday',                                         1, true),
('GR8DAD',   'OH', 'common',    'phonetic',           'Great dad',                                           1, true),
('SK8MOM',   'FL', 'common',    'phonetic',           'Skate mom',                                           1, true),
('CRE8IV',   'NY', 'common',    'phonetic',           'Creative',                                            1, true),
('B4UFLY',   'CO', 'common',    'phonetic',           'Before you fly',                                      1, true),
('IM L8',    'NV', 'common',    'phonetic',           'I''m late',                                           1, true),
('2FAST4U',  'MI', 'common',    'phonetic',           'Too fast for you',                                    1, true),
('LUV2LRN',  'MA', 'common',    'phonetic',           'Love to learn',                                       1, true),
('GR8DAY',   'TX', 'common',    'phonetic',           'Great day',                                           1, true),
('IMGR8',    'CA', 'common',    'phonetic',           'I''m great',                                          1, true),
('CUL8R',    'FL', 'common',    'phonetic',           'See you later',                                       1, true),
('BLESUP',   'GA', 'common',    'faith',              'Bless up',                                            1, true),
('UB4ME',    'NC', 'common',    'phonetic',           'You before me',                                       1, true),
('FUN2GO',   'OH', 'common',    'phonetic',           'Fun to go',                                           1, true),
('4GIVEN',   'TN', 'common',    'faith',              'Forgiven',                                            1, true),
('XLNT',     'NY', 'common',    'abbreviation',       'Excellent',                                           1, true),
('2KOOL',    'CA', 'common',    'phonetic',           'Too cool',                                            1, true),
('WHOOPS',   'TX', 'common',    'humor',              'Whoops',                                              1, true),
('NVRMND',   'WA', 'uncommon',  'abbreviation',       'Nevermind',                                           2, true),
('BCHLVR',   'SC', 'uncommon',  'abbreviation',       'Beach lover',                                         2, true),
('MTNBKR',   'MT', 'uncommon',  'abbreviation',       'Mountain biker',                                      2, true),
('WRKFRM',   'GA', 'uncommon',  'abbreviation',       'Work from home',                                      2, true),
('RTRDBBY',  'IN', 'uncommon',  'abbreviation',       'Retired baby boomer',                                 2, true),
('QTPI',     'TN', 'uncommon',  'abbreviation',       'Cutie pie',                                           2, true),
('DRPCFF',   'WI', 'uncommon',  'abbreviation',       'Drop coffee',                                         2, true),
('PLTRCK',   'PA', 'uncommon',  'abbreviation',       'Pool truck',                                          2, true),
('GLFPRO',   'AZ', 'uncommon',  'abbreviation',       'Golf pro',                                            2, true),
('NTRSTD',   'MN', 'uncommon',  'abbreviation',       'Not interested',                                      2, true),
('2QT4U',    'TX', 'uncommon',  'phonetic',           'Too cute for you',                                    2, true),
('BCLVR',    'SC', 'uncommon',  'abbreviation',       'Beach lover',                                         2, true),
('NE1HOME',  'WI', 'uncommon',  'phonetic',           'Anyone home',                                         2, true),
('YRUUP',    'CO', 'uncommon',  'phonetic',           'Why are you up',                                      2, true),
('NO1BUT',   'VA', 'uncommon',  'abbreviation',       'No one but',                                          2, true),
('W8NSEE',   'MN', 'uncommon',  'phonetic',           'Wait and see',                                        2, true),
('RUFNUF',   'AZ', 'uncommon',  'phonetic',           'Rough enough',                                        2, true),
('LIVNLRG',  'GA', 'uncommon',  'abbreviation',       'Living large',                                        2, true),
('BRB2IT',   'WA', 'uncommon',  'phonetic',           'Be right back to it',                                 2, true),
('RIZZGOD',  'CA', 'uncommon',  'humor',              'Rizz god',                                            2, true),
('10SNE1',   'CT', 'rare',      'phonetic',           'Tennis anyone',                                       3, true),
('ICURNVS',  'NJ', 'rare',      'phonetic',           'I see you are envious',                               3, true),
('4RUNNER',  'UT', 'rare',      'humor',              'Forerunner / Toyota 4Runner',                         3, true),
('XLNC',     'IL', 'rare',      'abbreviation',       'Excellency',                                          3, true),
('RU18YET',  'VA', 'rare',      'phonetic',           'Are you 18 yet',                                      3, true),
('IMAPYR8',  'ME', 'rare',      'phonetic',           'I''m a pirate',                                       3, true),
('OYL B4K',  'OK', 'rare',      'phonetic',           'I''ll be back',                                       3, true),
('RUOK2DY',  'MD', 'rare',      'phonetic',           'Are you okay today',                                  3, true),
('XQQQSME',  'KY', 'rare',      'phonetic',           'Excuse me',                                           3, true),
('Y YNT',    'NC', 'rare',      'phonetic',           'Why not',                                             3, true),
('ILVTOFU',  'OR', 'rare',      'humor',              'I love tofu',                                         3, true),
('RUDBKBY',  'NJ', 'rare',      'phonetic',           'Are you Debbie? / Rude but OK bye',                   3, true),
('XQSITME',  'IL', 'rare',      'phonetic',           'Exquisite me',                                        3, true),
('WNDRWHY',  'MI', 'rare',      'phonetic',           'Wonder why',                                          3, true),
('THNKTWC',  'PA', 'rare',      'abbreviation',       'Think twice',                                         3, true),
('MISNLGK',  'FL', 'rare',      'abbreviation',       'Missing link',                                        3, true),
('KPITRL',   'TX', 'rare',      'phonetic',           'Keep it real',                                        3, true),
('4EVRUS',   'VA', 'rare',      'phonetic',           'Forever us',                                          3, true),
('L8BLOOM',  'OH', 'rare',      'phonetic',           'Late bloomer',                                        3, true),
('NCC1701D', 'NM', 'epic',      'cultural reference', 'Star Trek USS Enterprise-D',                          4, true),
('OUTATYM',  'IL', 'epic',      'cultural reference', 'Out of time (Back to the Future)',                    4, true),
('KHAAAN',   'CA', 'epic',      'cultural reference', 'Khan (Star Trek II)',                                  4, true),
('MORDOR',   'WY', 'epic',      'cultural reference', 'Lord of the Rings',                                   4, true),
('LGRNG',    'TX', 'epic',      'cultural reference', 'LaGrange (ZZ Top / math)',                            4, true),
('T1000',    'MI', 'epic',      'cultural reference', 'Terminator T-1000',                                   4, true),
('RSHNMR',   'HI', 'epic',      'cultural reference', 'Rushmore (Wes Anderson film)',                        4, true),
('BYSFLCN',  'NV', 'epic',      'cultural reference', 'Millennium Falcon',                                   4, true),
('GANDLF',   'OR', 'epic',      'cultural reference', 'Gandalf (Lord of the Rings)',                         4, true),
('HODOR',    'MN', 'epic',      'cultural reference', 'Hodor (Game of Thrones)',                             4, true),
('MR BOND',  'VA', 'epic',      'cultural reference', 'James Bond',                                          4, true),
('42',       'CO', 'epic',      'cultural reference', 'Answer to everything (Hitchhiker''s Guide)',          4, true),
('OBI ONE',  'CA', 'epic',      'cultural reference', 'Obi-Wan Kenobi (Star Wars)',                          4, true),
('42FRDNT',  'CO', 'epic',      'cultural reference', '42 for Arthur Dent (Hitchhiker''s Guide)',           4, true),
('MYPRCS',   'KY', 'epic',      'cultural reference', 'My precious (Gollum, Lord of the Rings)',             4, true),
('RDDLME',   'DC', 'epic',      'cultural reference', 'Riddle me (Batman / The Riddler)',                    4, true),
('HLYWDMN',  'CA', 'epic',      'cultural reference', 'Hollywood man',                                       4, true),
('DNTSLP',   'NY', 'epic',      'cultural reference', 'Don''t sleep',                                        4, true),
('PSTMDRN',  'MA', 'epic',      'cultural reference', 'Postmodern',                                          4, true),
('CTRLALT',  'WA', 'epic',      'cultural reference', 'Control Alt Delete — IT culture reference',           4, true),
('N2DPRTH',  'AL', 'epic',      'phonetic',           'Into the depths / In too deep',                       4, true),
('WWJD',     'AL', 'epic',      'faith',              'What Would Jesus Do',                                 4, true),
('YLKNOW',   'TN', 'epic',      'phonetic',           'You''ll know / Y''all know',                         4, true),
('3MTA3',    'NH', 'legendary', 'humor',              'Reads EATME in mirror',                               5, true),
('YYURYYUB', 'VT', 'legendary', 'phonetic',           'Too wise you are too wise you be',                    5, true),
('NOTACRK',  'AL', 'legendary', 'abbreviation',       'Not a crook',                                         5, true),
('PEBCAK',   'WA', 'legendary', 'cultural reference', 'Problem Exists Between Chair And Keyboard',           5, true),
('LB4BRKR',  'MS', 'legendary', 'phonetic',           'Lawbreaker',                                          5, true),
('ROTFL',    'LA', 'legendary', 'abbreviation',       'Rolling on the floor laughing',                       5, true),
('7OF9',     'ID', 'legendary', 'cultural reference', 'Seven of Nine (Star Trek Voyager)',                   5, true),
('NWYMN',    'AK', 'legendary', 'abbreviation',       'No way man / Newman (Seinfeld)',                      5, true),
('XNTHILO',  'VT', 'legendary', 'foreign phrase',     'Ex nihilo (Latin: from nothing)',                     5, true),
('ZEN0SUM',  'CA', 'legendary', 'cultural reference', 'Zero sum (game theory)',                              5, true),
('MTRXDWN',  'IL', 'legendary', 'cultural reference', 'Matrix down (The Matrix)',                            5, true),
('SBLMNAL',  'NY', 'legendary', 'phonetic',           'Subliminal',                                          5, true),
('OVRTHNK',  'WA', 'legendary', 'abbreviation',       'Overthink',                                           5, true),
('QNTRMUP',  'NV', 'legendary', 'cultural reference', 'Quantum up / Quentin Tarantino',                      5, true),
('PRBLM8',   'TX', 'legendary', 'phonetic',           'Problem ate / Problem mate',                          5, true),
('TMSHFT',   'CO', 'legendary', 'abbreviation',       'Time shift',                                          5, true),
('NTLKTHT',  'MI', 'legendary', 'phonetic',           'Not like that',                                       5, true),
('COGITO',   'OR', 'legendary', 'foreign phrase',     'Cogito ergo sum (I think therefore I am)',            5, true)
ON CONFLICT DO NOTHING;
